# * Modify ecas-config.properties to contain the name of your website and port number.
# * Modify persistence.xml and environment for postgres to have matching information.

# VOLUMEDIR=/var/local/aqrsystem
# mkdir -p ${VOLUMEDIR}/config/WEB-INF/classes/META-INF
# mkdir -p ${VOLUMEDIR}/postgresqldata
# cp ecas-config.properties ${VOLUMEDIR}/config/WEB-INF/classes
# cp persistence.xml ${VOLUMEDIR}/config/WEB-INF/classes/META-INF
# 
# Copy the database files to ${VOLUMEDIR}/postgresqldata

# chcon -Rt svirt_sandbox_file_t ${VOLUMEDIR}

#
# Persistent files for Postgres
# Note that you'll have to manually inject the database files.
# To do so you create postgres alone with:
#    docker-compose up -d postgresqldata postgres
#    docker-compose stop postgres

#
# Container for postgres data. Note that the postgres:9.3 image defines a /var/lib/postgresql/data volume
# we must match.
#
postgresqldata:
    image: busybox
    volumes:
        - /etc/postgresql
        - /var/log/postgresql
        - /var/local/aqrsystem/postgresqldata:/var/lib/postgresql/data

#
# Start the Postgres Service
#
postgres:
    restart: always
    image: postgres:9.3
    environment:
        - POSTGRES_USER=aqraccount
        - POSTGRES_PASSWORD=dbpassword
        - POSTGRES_DB=aqrsystem
    volumes_from:
        - postgresqldata
    volumes:
        - /etc/localtime:/etc/localtime:ro # Share timezone data with host

#
# Persistent files for Tomcat
#
tomcatdata:
    image: busybox
    volumes:
        - /var/log/aqrsystem
        - /var/local/aqrsystem/tomcat-logs:/usr/local/tomcat/logs

# Start the Tomcat application
# Image is at https://hub.docker.com/r/eeacms/aqr-public/
tomcat:
    restart: always
    hostname: papers
    ports:
        - "8080:8080"
    image: dockerrepo.eionet.europa.eu:5000/aqrsystem
    links: 
        - postgres:DB_HOST
    volumes_from:
        - tomcatdata
    volumes:
        - /etc/localtime:/etc/localtime:ro # Share timezone data with host
        - /var/local/aqrsystem/config:/config:ro

