#
# VOLUMEDIR=/var/local/aqrsystem
# mkdir -p ${VOLUMEDIR}/postgresqldata
# 
# Copy the database files to ${VOLUMEDIR}/postgresqldata

# chcon -Rt svirt_sandbox_file_t ${VOLUMEDIR}

# * Modify the environment variables to fit.

#
# Persistent files for Postgres
# Note that you'll have to manually inject the database files.
# To do so you create postgres alone with:
#    docker-compose up -d postgresqldata postgres
#    docker-compose stop postgres

#
# Container for postgres data. Note that the postgres:9.3 image defines a /var/lib/postgresql/data volume
# we must match.
#
postgresqldata:
    image: busybox
    volumes:
        - /etc/postgresql
        - /var/log/postgresql
        - /var/local/aqrsystem/postgresqldata:/var/lib/postgresql/data
    labels:
        io.rancher.container.start_once: "true"
#       io.rancher.scheduler.affinity:host_label: hostname=swarm1-reportnet

#
# Start the Postgres Service
#
postgres:
    restart: always
    image: postgres:9.3
    environment:
        - POSTGRES_USER=aqraccount
        - POSTGRES_PASSWORD=dbpassword
        - POSTGRES_DB=aqrsystem
    volumes_from:
        - postgresqldata
    volumes:
        - /etc/localtime:/etc/localtime:ro # Share timezone data with host
    labels:
        io.rancher.sidekicks: postgresqldata

#
# Persistent files for Tomcat
#
tomcatdata:
    image: busybox
    volumes:
        - /var/log/aqrsystem
        - /var/local/aqrsystem/tomcat-logs:/usr/local/tomcat/logs
    labels:
        io.rancher.container.start_once: "true"
#       io.rancher.scheduler.affinity:host_label: hostname=swarm1-reportnet

#
# Start the Tomcat application
#
tomcat:
    restart: always
    hostname: papers
    ports:
        - "8080:8080"
    image: dockerrepo.eionet.europa.eu:5000/aqrsystem
    links: 
        - postgres:DB_HOST
    volumes_from:
        - tomcatdata
    volumes:
        - /etc/localtime:/etc/localtime:ro # Share timezone data with host
    labels:
        io.rancher.sidekicks: tomcatdata
    environment:
        - SERVER_NAME=localhost
        - SERVER_PORT=8080
        - DB_URL=jdbc:postgresql://DB_HOST:5432/aqrsystem
        - DB_USERNAME=aqraccount
        - DB_PASSWORD=dbpassword
        - DB_DRIVER=org.postgresql.Driver

